### ISSUE TITLE
Top-level Jacobian only works with integer argnum (not list)

### ISSUE THREAD

**Issue by co9olguy** [XanaduAI/pennylane#112]
This seems to be due to a bug in how we are interfacing with autograd, or -- less likely -- a bug in autograd itself.

If the user provides a quantum function `func` with multiple input arguments in its signature, we can only successfully call `qml.jacobian(func, argnum=0)`, `qml.jacobian(func, argnum=1)`, etc., but not `qml.jacobian(func, argnum=[0,1])` (raises some error inside autograd). 

Since we've coded `jacobian` to behave nicely if all the arguments are combined into an array, a suitable alternate usage is available. Would be nice to figure this bug out at some stage

**Comment by cgogolin** [comment]
But `qml.jacobian()` could still be enabled to allow `argnum` to be a list. `jacobian(func, argnum)` is anyway already a shallow wrapper around the actual autograd `jacobian` that we import as `_jacobian`. This wrapper could just return a lamda function that can call `_jacobian` for all elements or `argnum`.

The way things are at the moment, this is a bug, because the documentation claims that `argnum` can be a numpy array (in the description of the argument) but at the same time specifies it to be a of type `(int)`. I will submit a PR in a second.
