### ISSUE TITLE
Supply templates for QML models

### ISSUE THREAD

**Issue by cgogolin** [XanaduAI/pennylane#133]
It would be useful to provide users with templates for the most common QML modes in the form of functions that can be directly called in a qnode to construct the corresponding circuit.

**Comment by cgogolin** [comment]
Maybe it would make the syntax nice to use Capital case for the models? This would make them better fit in with the existing Operations?

**Comment by josh146** [comment]
Yes, that makes sense. Something like this? (psuedo-code)
```python
from pennylane.models import Classifier, QGAN

@qml.qnode(dev1)
def f(x):
   Classifier(x, wires=[0, 1, 2])
```

**Comment by cgogolin** [comment]
I can also make it a class and implement `__init__()`?

**Comment by co9olguy** [comment]
While I generally favour the idea, I'm having trouble seeing which models this might apply to. Things like `Classifier` and `QGAN` are themselves not single models, but large *model classes*. These classes will cover a wide range of possible architecture choices. And there will be no obvious canonical "best" choice, because "best" depends on the data/task, and also because these models are still largely unexplored.

Is there something more specific that you think falls within this rubric (e.g., a subcircuit/subroutine? or an ansatz?)

**Comment by cgogolin** [comment]
Yes, that is exactly what I was aiming at.
