### ISSUE TITLE
Weight Initialization

### ISSUE THREAD

**Issue by kareem1925** [XanaduAI/pennylane#139]
Hi,
In this [Notebook](https://github.com/XanaduAI/pennylane/blob/master/examples/CV2_quantum-neural-net.ipynb) you initialized the weights in shape of (4,7) actually I tried to modify this many times but none were good as your implementation's output. Is there a way to find a general way of initializing weights? there are many ways in deep neural networks but do they fit in for quantum?
my guess is that it has something to do with the number of gates right? because I know the first parameter is the  number of layers. what about the second one?!

**Comment by josh146** [comment]
Hi @kareem1925. The GitHub issue tracker is for reporting bugs and issues with PennyLane. For discussion over machine learning approaches and techniques, the best place is the [PennyLane forums](https://discuss.pennylane.ai).

I'm closing this issue here. Feel free to copy your question over to the discussion forums, and I'll see if @mariaschuld can take a look.

**Comment by kareem1925** [comment]
Server error :cry: 
![image](https://user-images.githubusercontent.com/30449261/49601739-5797b600-f98f-11e8-86d3-03a7a256c430.png)

**Comment by kareem1925** [comment]
I'm sorry for any disturbance

**Comment by josh146** [comment]
That is strange - it appears to be working fine on my end!

Can you try copying your text, refreshing the page, and trying to post it again?

**Comment by kareem1925** [comment]
i've done that already but nothing happened 
any way i opened an old topic and mentioned you 
thanks for response ^_^
