### ISSUE TITLE
Restructure templates

### ISSUE THREAD

**Issue by mariaschuld** [XanaduAI/pennylane#174]
My suggestion is the following:

* Make templates a folder/module with submodules
* distinguish templates.layers (for what people so far use as layered ansatze) and templates.embeddings (following the literature on input embeddings)
*   For each template we have a template.utils function that generates random parameters of the right shape
* We make sure that every template uses only square arrays so it's compatible with pytorch!
* A detail on naming: Christian named the template methods LikeThis(), even though they are not classes. Keep or change to python standard? Secondly, I would name layers templates bla_layers or bla_layer and embeddings bla_embedding...

**Comment by mariaschuld** [comment]
@co9olguy and @josh146, can we take a vote on the suggestions?

**Comment by josh146** [comment]
> Make templates a folder/module with submodules

I agree. Not only will this make it easier to document, it will be cleaner to work with, write unit tests for, and also easier for people to add to/modify in PRs.

> distinguish templates.layers (for what people so far use as layered ansatze) and templates.embeddings (following the literature on input embeddings)

Agree here as well. Any reason behind choosing `templates.embeddings` instead of `templates.encodings`?

> We make sure that every template uses only square arrays so it's compatible with pytorch!

I agree. This should also help with TF compatibility.

> A detail on naming: Christian named the template methods LikeThis(), even though they are not classes. Keep or change to python standard? Secondly, I would name layers templates bla_layers or bla_layer and embeddings bla_embedding...

I think the reasoning behind this was so that it kept the same convention as the other quantum operations, i.e.

```python
def circuit():
    qml.Rot(0.5, 30.1, 0.1, wires=0)
    qml.StronglyEntanglingCircuit(wires=[0,1])
```

While this goes against PEP8, I'm actually in favour of keeping this convention, as it keeps the UI consistent for the user. I'm open to thoughts on this though.

**Comment by co9olguy** [comment]
No issue with any of the proposals. In fact, I'd even be in favour of changing *all* quantum operations to lowercase (better matches with numpy, pytorch, tensorflow notation, etc.). I think the reason they were uppercase originally is because the simplest ops (gates, measurements) were all named after operators (`CNOT`, `Hadamard` etc).

**Comment by mariaschuld** [comment]
Picking this up again. I will keep upper case convention for now. 

No strong opinion on embeddings or encodings, but embeddings carries more meaning towards a feature map into Hilbert space...Any preference @co9olguy ?

**Comment by mariaschuld** [comment]
We can simply discuss wording in the code review, I will make a proposal for now.
