### ISSUE TITLE
Support QubitUnitary() with more than two wires

### ISSUE THREAD

**Issue by Raycosine** [XanaduAI/pennylane#176]
Similar to #170 & #175.
It's better for simulation to support arbitrary quantum gates with more than two wires(CSWAP for example), though impractical for plugins about quantum devices to some extent.

the [source code](https://pennylane.readthedocs.io/en/latest/_modules/pennylane/plugins/default_qubit.html#DefaultQubit.apply) implies that more than two wires are not allowed:

```
        # apply unitary operations
        if len(wires) == 1:
            U = self.expand_one(A, wires)
        elif len(wires) == 2:
            U = self.expand_two(A, wires)
        else:
            raise ValueError('This plugin supports only one- and two-qubit gates.')
```
and just copy the error information here:

> /usr/local/lib/python3.6/dist-packages/pennylane/decorator.py in wrapper(*args, **kwargs)
>     151         def wrapper(*args, **kwargs):
>     152             """Wrapper function"""
> --> 153             return qnode(*args, **kwargs)
>     154 
>     155         # bind the jacobian method to the wrapped function
> 
> /usr/local/lib/python3.6/dist-packages/pennylane/qnode.py in __call__(self, *args, **kwargs)
>     455         # pylint: disable=no-member
>     456         args = autograd.builtins.tuple(args)  # prevents autograd boxed arguments from going through to evaluate
> --> 457         return self.evaluate(args, **kwargs)  # args as one tuple
>     458 
>     459     @ae.primitive
> 
> /usr/local/lib/python3.6/dist-packages/autograd/tracer.py in f_wrapped(*args, **kwargs)
>      46             return new_box(ans, trace, node)
>      47         else:
> ---> 48             return f_raw(*args, **kwargs)
>      49     f_wrapped.fun = f_raw
>      50     f_wrapped._is_autograd_primitive = True
> 
> /usr/local/lib/python3.6/dist-packages/pennylane/qnode.py in evaluate(self, args, **kwargs)
>     510             check_op(op)
>     511 
> --> 512         ret = self.device.execute(self.queue, self.ev)
>     513         return self.output_type(ret)
>     514 
> 
> /usr/local/lib/python3.6/dist-packages/pennylane/_device.py in execute(self, queue, expectation)
>     206             self.pre_apply()
>     207             for operation in queue:
> --> 208                 self.apply(operation.name, operation.wires, operation.parameters)
>     209             self.post_apply()
>     210 
> 
> /usr/local/lib/python3.6/dist-packages/pennylane/plugins/default_qubit.py in apply(self, operation, wires, par)
>     324             U = self.expand_two(A, wires)
>     325         else:
> --> 326             raise ValueError('This plugin supports only one- and two-qubit gates.')
>     327 
>     328         self._state = U @ self._state
> 
> ValueError: This plugin supports only one- and two-qubit gates.

**Comment by josh146** [comment]
Hi @Raycosine! The reason the `default.qubit` plugin only supports one- and two-qubit gates is because it is designed to be a very simple and basic reference plugin, provided mostly as a guide for plugin developers (and a useful reference to run our unit tests against). As a result, it is not optimized for high performance, and only supports limited features (i.e., maximum of two-qubit operations/expectations, no mixed state simulations, etc.).

In general, we would suggest using a plugin for a specialized qubit simulator (for example, either [PennyLane-Forest](https://github.com/rigetti/pennylane-forest) or [PennyLane-ProjectQ](https://github.com/xanaduai/pennylane-pq)) for production code.

At the same time, if you would like to submit a PR adding support for `QubitUnitary` for more than two wires to the `default.qubit` device, we'd be more than happy!

**Comment by Raycosine** [comment]
Thanks @josh146 ! It's my fault never trying those plugins lol.
