### ISSUE TITLE
Operations on parameters inside qnodes

### ISSUE THREAD

**Issue by artix41** [XanaduAI/pennylane#177]
Is there a way to make the following code work?

```python
@qml.qnode(dev1, interface='torch')
def test(theta):
    qml.RY(theta)
    qml.RZ(theta/2)
    return qml.expval.PauliZ(0)
test(1)
```

For the moment, it returns:
`TypeError: unsupported operand type(s) for /: 'Variable' and 'int'`

**Comment by josh146** [comment]
Hi @artix41, I've created a new pull request (see #179) to implement parameter division.

In the meantime, scalar multiplication of parameters is already supported, so replacing `/2` with `*0.5` will work:

```python
@qml.qnode(dev1, interface='torch')
def test(theta):
    qml.RY(theta, wires=0)
    qml.RZ(theta*0.5, wires=0)
    return qml.expval.PauliZ(0)
```

**Comment by artix41** [comment]
Great, thanks!

**Comment by frederikwilde** [comment]
This is related to the above issue, but not the same.
Is there a reason why one can't add or multiply arguments within qnodes?

```python
device = qml.device('default.qubit', wires = 1)
@qml.qnode(device)
def circuit(z1, z2):
    qml.RZ(z1 * z2, wires = 0)
    return qml.expval.PauliZ(0)
circuit(1., 2.)
```
gives: 
`TypeError: unsupported operand type(s) for /: 'Variable' and 'int'`
in line 174 `return expm(-1j * theta/2 * Z)` in plugins/default_qubit.py

**Comment by josh146** [comment]
Hi @frederikwilde. The main reason we don't support this is technical. 

In PennyLane, all free parameters passed as QNode arguments are wrapped in a `Variable` object, in order to allow us to keep track of which operations depend on which parameters, which is required for things such as parameter fan-out.

Limited scalar operations on `Variable` objects, such as `theta/2` as discussed above, simply returns _the same variable object_, which doesn't affect the way we deal with autodifferentiation. However, operations between multiple variables inside a quantum operation would return *a different variable object*, and we lose the ability to track the original two variables that were multiplied together.

**Comment by frederikwilde** [comment]
Ah, I see. Thanks for explaining :-)
