### ISSUE TITLE
Installation docs: add link to the github page and explaining cloning

### ISSUE THREAD

**Issue by AroosaIjaz** [XanaduAI/pennylane#198]
1. having a link to pip (https://pypi.org/project/pip/)

2. mentioning that the install command needs to be written in the terminal and where one can find the terminal for Windows/Linux

3. second install option of "installing from the source code" can seem vague. We can have the link to pennylane github page here, explain how to clone the repository and install from it step by step separately for Windows and Linux.

4. Maybe we can two tabs for install instructions for Windows and Linux?

**Comment by josh146** [comment]
Hi @AroosaIjaz! Thanks for your comments. We're always looking for how to make PennyLane easier to install and use via our documentation

> having a link to pip (pypi.org/project/pip)

`pip` is currently pre-installed with all modern Python installations, so this may confuse the user (especially since the linked page says to use `pip install pip` to install pip)

> mentioning that the install command needs to be written in the terminal and where one can find the terminal for Windows/Linux

While we want to ensure the installation instructions are as complete as possible, at some point we need to draw a line between what we should consider 'common knowledge' for someone who comes across PennyLane (someone who is likely familiar with Python and running Python scripts on the terminal).

Unfortunately, attempting to specify OS dependent details creates new issues, in that the location of the terminal (and even the name of the terminal program) can vary greatly depending on how Python is installed (i.e., CPython vs. Anaconda), the operating system version (Windows 8 vs Windows 10) and, in the case of linux, the desktop environment used.

We used to have more specific installation instructions with Strawberry Fields, but found that it led to more confusion when the users system didn't exactly match what we provided. Paring it back to a simple `pip install` command seemed to work a lot better, and led to fewer user questions on installation.

> second install option of "installing from the source code" can seem vague. We can have the link to pennylane github page here, explain how to clone the repository and install from it step by step separately for Windows and Linux.

In general, we would like most people to install via `pip`. Installing from source code should only be considered by either (a) developers, or (b) users interested in trying out beta code and features, and providing feedback. As before, the steps required to install `git` vary widely depending on the OS/linux distribution.

One thing we could do is provide the full codeblock:

```python
git clone https://github.com/XanaduAI/pennylane
cd pennylane
pip install -e .
```

Perhaps we could come up with a better section title than 'installing from source code'.

**Comment by AroosaIjaz** [comment]
Thanks a lot for your detailed review! :)

**Comment by co9olguy** [comment]
Any reason why this was closed? I think there are some suggestions here that we could definitely incorporate

**Comment by AroosaIjaz** [comment]
I already added these suggestions to the new documentation.
