### ISSUE TITLE
Unclear for user that "QubitStateVector" only acts on all wires of device

### ISSUE THREAD

**Issue by mariaschuld** [XanaduAI/pennylane#255]
When using QubitStateVector() (i.e., in AmplitudeEmbedding template), but one attempts to only use a subset of wires, one gets an error about the state not having 2**num_wires entries. However locally, both variables "state" and "wires" at that point have the correct size, so it's very hard to trace the reason.

I assume this is because QubitStateVector() can only deal with all wires at this stage. But in that case it should either not have a "wires" argument at all, OR the documentation should mention that it cannot deal with subsets of wires, OR the exception is clear.

I propose for now just to update the docs.

**Comment by josh146** [comment]
> I assume this is because QubitStateVector() can only deal with all wires at this stage

Right.

> But in that case it should either not have a "wires" argument at all

At the moment, all operations are defined simply by inheriting the `Operation` class, and defining class attributes. I'm in favor of removing the `wires` argument from operations that only apply to the entire subsystem; two ways of doing this are:

* Manually overwritting `__init__` in `QubitStateVector`. Ugly, would look out of place with other operations, but would be straightforward and explicit.

* Modify `Operation`, so that a particular value of the `num_wires` class attribute will correspond to 'the full subsystem', and make `wires` an optional keyword argument. Potentially more elegant, but could be prone to edge cases. This would involve the following modification to `Operation`:

  ```python
  def __init__(self, *args, wires=None, do_queue=True):
      # pylint: disable=too-many-branches
      self.name = self.__class__.__name__   #: str: name of the operation

      if self.num_wires == 'all': # or some other non-string value
          if do_queue:
              wires = QNode._current_context.num_wires

      if wires is None:
          raise ValueError("Must specify the wires that {} acts on".format(self.name))
   ```

**Comment by co9olguy** [comment]
How come overwriting `__init__` would be ugly?

**Comment by josh146** [comment]
Because we structured the `ops/` module such that no overwriting of `__init__` should ever be necessary --- all operations are simply classes with attributes. E.g.,
```python
class Hadamard(Observable, Operation):
    r"""Hadamard(wires)
    The Hadamard operator

    .. math:: H = \frac{1}{\sqrt{2}}\begin{bmatrix} 1 & 1\\ 1 & -1\end{bmatrix}.

    **Details:**

    * Number of wires: 1
    * Number of parameters: 0

    Args:
        wires (Sequence[int] or int): the wire the operation acts on
    """
    num_params = 0
    num_wires = 1
    par_domain = None
```

So ugly in the sense that it is (a) inconsistent with all other operations, and (b) would show up in the user facing 'supported operation' documentation page.

---

My preference would be to modify the `Operation` base class directly to automatically support operations that specify (a) `num_wires = 'all'`, or (b) `num_wires = 'any`'.

**Comment by co9olguy** [comment]
makes sense, especially if we add in more operations which cover all wires in future

**Comment by AroosaIjaz** [comment]
I can do a PR on this. Also, the grad_method for QubitStateVector is the "F" method. Should it not be "None"? This is a state preparation method and should not depend on any parameters in principle, no?

**Comment by josh146** [comment]
I'm working on the full solution currently :)
