### ISSUE TITLE
Add matrices, eigenvectors and eigenvalues to operators

### ISSUE THREAD

**Issue by johannesjmeyer** [XanaduAI/pennylane#297]
We should probably add the corresponding matrices, eigenvalues and eigenvectors to certain selected operators (mostly the Paulis), because they tend to pop up in quite a few places. It was needed for the GradientTensorOptimizer and currently I also need it in the Cirq plugin.

Maybe the implementation could be delegated to the plugins where you are sure what convention is used.

**Comment by co9olguy** [comment]
Nice idea @johannesjmeyer. I see no reason why we can't keep basic "meta-data" as simple attributes of these classes

**Comment by josh146** [comment]
I agree :+1:

On the other hand, I'm surprised that you need access to the matrices in the Cirq plugin - from my experience with the other plugins, this has never been the case. Can I ask what is the use-case here?

**Comment by johannesjmeyer** [comment]
The same issue as in the Qiskit-plugin. In simulation mode, Cirq will only give me the state from which I have to calculate the expectation values by hand. Technically, I only need the eigenvalues of the matrices to convert it back but I still need the information.

**Comment by co9olguy** [comment]
This feature would be nice to have whenever we are implementing sampling in simulator plugins. Currently every simulator has a hand-coded matrix representation, and all the xanadu-maintained plugins use singular value decompositions to get the eigenvectors/eigenvalues. Since these never change, it would be good to somehow just query one spot in pennylane core where this information is saved.

**Comment by johannesjmeyer** [comment]
I agree, this is also mentioned (at least partly) in the ADR concerning the plugin functionality that should go to PL core.
