### ISSUE TITLE
Black codebase

### ISSUE THREAD

**Issue by co9olguy** [XanaduAI/pennylane#302]
Currently files are getting `black`ed on the fly, i.e., if they are modified as part of an incoming PR. It would make more sense to just have a single PR which `black`s the entire codebase (or module-by-module) to make code review easier.

**Comment by smite** [comment]
I'd go as far as "don't run black on a file if you also make other modifications to it", since otherwise it's very time-consuming for the reviewers to decide which changes they should be looking at.

**Comment by johannesjmeyer** [comment]
I agree that this is a good idea, but to do this no other PRs should be on hold, because after merging the blacking merging the other PRs will be a pain in the ass.

Also, just running black -l 100 on the whole codebase might give some suboptimal results. For example, I intended to black `test_default_qubit.py` after the refactor (the whole code has changed too much anyways), but I refrained from it because it unrolled the `mark.parametrize` statements in a way that was just unreadable. I also did not find a way to tell black to exclude those lines from blacking.

**Comment by josh146** [comment]
> I agree that this is a good idea, but to do this no other PRs should be on hold, because after merging the blacking merging the other PRs will be a pain in the ass.

I agree - I have been sitting on this, waiting for the number of existing PRs to reduce so that the black PR could be made. Hopefully leading up to the next release.

> I also did not find a way to tell black to exclude those lines from blacking.

You can add `# fmt: off` before the code section that shouldn't be blacked, and `# fmt: on` afterwards. I also do this around large NumPy matrices; black oftens formats them like JSON datastructures.
