### ISSUE TITLE
In-place modification of operations in the queue

### ISSUE THREAD

**Issue by co9olguy** [XanaduAI/pennylane#360]
In addition, it feels hacky to pull ops out of the queue just to update return_type, then put them right back. There are three potential solutions, which differ in scope:

* Re-think the queuing behaviour across the board (probably too hard)

* Remove queuing from just observables (since it is not needed), and have the expval/sample/var functions perform the queuing

* See if it's possible to find and update the observable in the queue, without removing it?

I'm thinking option number (2) is preferable.

_Originally posted by @josh146 in https://github.com/XanaduAI/pennylane/issues/161#issuecomment-540121666_

**Comment by josh146** [comment]
@smite noted in a PR that queuing of observables prior to calling the measurement function has one advantage: it provides validation and allows us to raise an error if an observable is used like a quantum operation. Otherwise, option (2) would cause observables within the operation queue to go 'un-noticed' and do nothing.

Option 3 (modifying in-place) would in that case be preferable.

**Comment by smite** [comment]
Another related issue is that currently some Observables are also Operations, PauliX for example. I think it would be cleaner to split it into two classes, PauliX_as_a_gate and PauliX_as_an_observable. This has the advantage that every Observable instance would be an actual observable, and the queuing would get simpler.

**Comment by johannesjmeyer** [comment]
As the API is laid out right now, you won't be able to do option (2) simply because of what @smite mentioned. As the measurement functions (e.g. `qml.var`) are called after the initialization of the Observable, we simply can not know at the time of initialization if a `PauliX` is used as an Observable or an Operation.

Note that I am still against having `PauliX` and `PauliXObservable` as separate entities because this will make no sense to the user.

Now on to what we can do: Actually, the operation would already be modified in place if they were not taken out of the queue. So what if we just queue all Operators in one queue and do all sanity checks that can sensibly be done at that point. Then, after the qfunction is executed, we sort the operators and observables into separate queues and do the additional sanity checks. This would make the measurement functions far easier, because they only come down to setting a return_type. And the triage happening after the function makes a lot of sense because this is the point where we have access to that information.

This is a small change and I quickly cooked it up, please have a look at PR #391 

There are still 80 failing tests, due to tensor reasons. I think it is a little bit weird that Tensor observables don't queue. I did not closely follow the implementation, but I would have expected that the Tensor operation queues itself and removes its constituent operations from the queue at the same time.

**Comment by josh146** [comment]
@johannesjmeyer, I believe this is now solved after merging #548, let me know if this is not the case.

**Comment by johannesjmeyer** [comment]
This is not "solved" in my opinion. It will only be (in my opinion) after the delete from queue / reinsert logic is removed from the measurement functions.
________________________________
