### ISSUE TITLE
Issues with the templates random_layers_normal and random_layers_uniform

### ISSUE THREAD

**Issue by AroosaIjaz** [XanaduAI/pennylane#383]
#### Issue description

There is some issue with the initialization template for random layers `random_layers_normal` and `random_layers_uniform`. see the simple code below:

```python
import pennylane as qml
from pennylane import numpy as np
from pennylane.templates.embeddings import AmplitudeEmbedding
from pennylane.templates.layers import RandomLayers
from pennylane.init import random_layers_normal

dev = qml.device('default.qubit', wires=2)

def circuit(weights, p=None):
    AmplitudeEmbedding(p, wires=[0,1])
    RandomLayers(weights, wires=[0,1], ratio_imprim=0.5, seed=2)
    return qml.expval(qml.PauliZ(0))
```

``` python
weights_init = random_layers_normal(n_layers=2, n_wires=2, seed=1)
print(weights_init)
print(len(weights_init))
```
```
[array([[ 0.16243454, -0.06117564],
       [-0.05281718, -0.10729686]])]
1
```
The shape of the output is wrong. it should be (2,2) array. 
so when `RandomLayers` template wants to break this down to get weights for each layer:

```python
for layer_weights in weights_init:
    print(layer_weights)
    break
``` 
```
[[ 0.16243454 -0.06117564]
 [-0.05281718 -0.10729686]]
```
it gets the whole array. this means that when `RandomLayers` wants to call `RandomLayer` for each layer, the weights dimensions are wrong to do rotations in each layer:

```python
qnode = qml.QNode(circuit, dev)
test = np.array([0, 1, 0, 0])
print(qnode(weights_init, p=test))
```
`TypeError: RZ: Real scalar parameter expected, got <class 'numpy.ndarray'>.`

The same thing happens with `random_layers_uniform` template.

**Comment by AroosaIjaz** [comment]
This could be because the init functions do the following:

```python
params = np.random.uniform(low=low, high=high, size=(n_layers, n_rots))
return [params]
```
To avoid the issue above, we can use:

`return np.asarray(params)`

**Comment by AroosaIjaz** [comment]
I have not checked all other initialization templates but it may hold for others too.

**Comment by AroosaIjaz** [comment]
I see a similar issue when I tried to use `StronglyEntanglingLayer`. I will make a PR on this.

**Comment by josh146** [comment]
Hi @AroosaIjaz, thanks for looking into this. A couple of things I noticed while working on the templates last week:

* Having the initialization functions return `[params]` is intentional, as it allows the discrete variable templates to match the CV templates (which have more than one argument, i.e., `Interferometer(theta, phi, varphi, wires=[0, 1])`. After you initialize parameters, you then pass them via tuple unpacking:

  ```python
  import pennylane as qml
  from pennylane.templates.embeddings import AngleEmbedding
  from pennylane.templates.layers import StronglyEntanglingLayers
  from pennylane.init import strong_ent_layers_uniform
  
  dev = qml.device('default.qubit', wires=2)
  
  @qml.qnode(dev)
  def circuit(weights, x=None):
      AngleEmbedding(x, [0,1])
      # we use *weights to 'unpack' [weights]
      StronglyEntanglingLayers(*weights, wires=[0,1])
      return qml.expval(qml.PauliZ(0))
  
  init_weights = strong_ent_layers_uniform(n_layers=3, n_wires=2)
  print(circuit(init_weights, x=[1., 2.]))
  ```

* Note that this doesn't match the [templates introduction](https://pennylane.readthedocs.io/en/latest/introduction/templates.html) in the docs, where tuple unpacking is not used. The reason the docs version works is that it is using `strong_ent_layer_uniform` (note, `layer`, not `layers`)! This is likely a typo that needs to be fixed.

That being said, I have to agree with you, I find the templates a bit confusing to work with (I had the same train of thought as your issue all last week, until I finally spotted the missing 's' in the docs).

Perhaps the best solution(s) would be:

1. Have all templates simply accept a flat array `weights`. In most cases, we don't tend to care what the particular `phi`, `varphi`, etc. values are; and when we do need them, we can index them specifically.

2. Remove the 'one layer' parameter initialization functions, or make them private. The 'layers' version is sufficient for all cases (because you can set `n_layers=1` if needed.

**Comment by AroosaIjaz** [comment]
@josh146 , Thank you for the detailed response. 

> Note that this doesn't match the templates introduction in the docs, where tuple unpacking is not 
> used. The reason the docs version works is that it is using strong_ent_layer_uniform (note, layer, 
> not layers)! This is likely a typo that needs to be fixed.

Ah yes, I just noticed the use of a single layer in the template introduction page!

The docs of the initialization functions do not mention this 'packing' and state that they return an array of shape (n_layers, n_rots). 

> Perhaps the best solution(s) would be:
> 
> 1. Have all templates simply accept a flat array `weights`. In most cases, we don't tend to care what > the particular `phi`, `varphi`, etc. values are; and when we do need them, we can index them 
> specifically.

Agreed. The PR #384 takes care of this, right?

> 2. Remove the 'one layer' parameter initialization functions, or make them private. The 'layers'
> version is sufficient for all cases (because you can set `n_layers=1` if needed.

Agreed. I will wait for @mariaschuld 's feedback on this and then add this to the current PR.

**Comment by AroosaIjaz** [comment]
> * Having the initialization functions return `[params]` is intentional, as it allows the discrete variable templates to match the CV templates (which have more than one argument, i.e., `Interferometer(theta, phi, varphi, wires=[0, 1])`. After you initialize parameters, you then pass them via tuple unpacking:


knowing this would have saved me a couple of hours yesterday :D

**Comment by mariaschuld** [comment]
Yes, we took the decision for a counterintuitive "[...]", but in favour of having all templates act the same. 

I think this is another nudge to sit down and simplify the templates, especially before we systematically fill the modules with more circuits. It's on my todo list in the medium/short term.

Since this isn't (at this stage) a bug in the code, shall we just fix the example in the docs and add a warning for now, and then do a proper makeover in a separate PR?

**Comment by AroosaIjaz** [comment]
sound good @mariaschuld. The docstrings and the example in the intro can be updated for now.

**Comment by AroosaIjaz** [comment]
Let us keep this open as a reminder until we update the templates. 

dear @mariaschuld,  will you be taking care of this? or should I make a PR? :)

**Comment by mariaschuld** [comment]
Could you do a quick fix? Thanks!!

**Comment by AroosaIjaz** [comment]
@josh146, @mariaschuld should I go ahead and add a line to each template function docstring that we have to unpack the parameters? Is that still ok or are we changing this feature to make them compatible with TensorFlow as discussed in the meeting today?

**Comment by josh146** [comment]
@AroosaIjaz: @mariaschuld is currently working on an ADR regarding the templates, so let's wait until that is merged in 🙂

**Comment by mariaschuld** [comment]
@AroosaIjaz If the templates ADR gets approved quickly we can just do the proper update. If it takes longer I would kindly ask you to do exactly that.

**Comment by Sanjeev-sap** [comment]
I could not import  "from pennylane.init import strong_ent_layers_uniform" I am getting the same error "ModuleNotFoundError: No module named 'pennylane.init'". I searched for documents on Pennylane but didn't find it. Could you please help me to import this library. Thank you.

**Comment by josh146** [comment]
Hi @Sanjeev-sap! `pennylane.init` has since been deprecated and removed from PennyLane. 

The new way to initialize template parameters is like so

```python
shape = qml.StronglyEntanglingLayers.shape(n_layers=2, n_wires=4)
weights = np.random.random(size=shape)
```

You can see more examples in the documentation: 

https://docs.pennylane.ai/en/stable/code/api/pennylane.StronglyEntanglingLayers.html
